import { MockPersona } from '../../_shared/types/mockPersona';

export const mockPersonas: MockPersona[] = [
  {
    title: 'Franco',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-11.png',
    createdAt: 0,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'VLK',
    src: 'https://miro.medium.com/max/800/1*zslyy_N64PbkRflC3mOeoQ.jpeg',
    createdAt: 1,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Francesco',
    src: 'https://cdn.domestika.org/c_fit,dpr_auto,f_auto,t_base_params,w_820/v1601931948/content-items/005/934/025/User_Persona-original.png?1601931948',
    createdAt: 2,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Figma',
    src: 'https://assets.justinmind.com/wp-content/uploads/2020/07/young-working-student-user-persona.png',
    createdAt: 3,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Figma',
    src: 'https://clearbridgemob-wpengine.netdna-ssl.com/wp-content/uploads/2016/06/userpersonaapp.png',
    createdAt: 4,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Figma',
    src: 'https://i1.wp.com/assets.productschool.com/wp-content/uploads/2019/05/14083916/persona-24-24_2x.png',
    createdAt: 5,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://assets.justinmind.com/wp-content/uploads/2020/07/user-persona-template-data-analyst.png',
    createdAt: 6,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-6.png',
    createdAt: 8,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-7.png',
    createdAt: 9,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-9.png',
    createdAt: 10,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-6.png',
    createdAt: 121,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-2.png',
    createdAt: 431,
    updatedAt: 0,
    type: 'persona',
  },
  {
    title: 'Test',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-1.png',
    createdAt: 4985,
    updatedAt: 0,
    type: 'template',
  },
];
