import { MockPersona } from '../../_shared/types/mockPersona';

export const mockTemplate: MockPersona[] = [
  {
    title: 'Franco',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-2.png',
    createdAt: 0,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-3.png',
    createdAt: 2,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-1.png',
    createdAt: 3,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://i1.wp.com/assets.productschool.com/wp-content/uploads/2019/05/14083916/persona-24-24_2x.png',
    createdAt: 4,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-7.png',
    createdAt: 5,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://i1.wp.com/assets.productschool.com/wp-content/uploads/2019/05/14083916/persona-24-24_2x.png',
    createdAt: 6,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-8.png',
    createdAt: 7,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-9.png',
    createdAt: 8,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-11.png',
    createdAt: 9,
    updatedAt: 0,
    type: 'template',
    author: 'Frank',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-12.png',
    createdAt: 10,
    updatedAt: 0,
    type: 'template',
    author: 'default',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-6.png',
    createdAt: 11,
    updatedAt: 0,
    type: 'template',
    author: 'default',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-6.png',
    createdAt: 12,
    updatedAt: 0,
    type: 'template',
    author: 'default',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-6.png',
    createdAt: 13,
    updatedAt: 0,
    type: 'template',
    author: 'default',
  },
  {
    title: 'VLK',
    src: 'https://www.susannafer.com/wordpress/wp-content/uploads/2020/10/esempio-personas-template-6.png',
    createdAt: 14,
    updatedAt: 0,
    type: 'template',
    author: 'default',
  },
];
